name: Test
on: [push, pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry and run it
        run: | 
          python -m pip install poetry
          python -m poetry install

      - name: Run Tests with Pytest and Coverage
        run: |
          # Run the tests with coverage and generate the badge
          poetry run coverage run -m pytest --junitxml=reports/tests/tests.xml --html=reports/tests/report.html
          poetry run genbadge tests --input-file=reports/tests/tests.xml --output-file=reports/tests/tests-badge.svg
          # Generate the coverage and the badge
          poetry run coverage html
          poetry run coverage xml
          poetry run genbadge coverage --output-file=reports/coverage/coverage-badge.svg

      - name: Commit and push badge
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add reports
          git commit -m "Added reports"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PYTEST_COVERAGE_COMMENT }}
